name: test-secret
run-name: ${{ github.actor }} is testing out secret Map
on:
  push:
    branches:
      - test
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      APIKEY: ${{ secrets.APIKEY }}
      FILE: ${{ github.workspace }}
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: sed -i 's/MAP_API_KEY/$APIKEY/g' $FILE/src/index.html
      - run: npm install -g @angular/cli@17
      - run: npm install
      - run: ng build --output-path docs --base-href ${{ github.workspace }}/
      - run: mv $FILE/docs/browser/* $FILE/docs/
      - run: cp $FILE/docs/index.html $FILE/docs/404.html
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
          verbose: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site
          retention-days: 1
      - name: Deploy 
        uses: actions/deploy-pages@v3
        with:
          token: ${{ github.token }}

      
      
