name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - test
jobs:
  set-key-api:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: sed -i 's/MAP_API_KEY/$APIKEY/g' $FILE/src/index.html
        env:
          APIKEY: ${{ secrets.APIKEY }}
          FILE: ${{ github.workspace }}
      
      
